site_url: https://webssh.net
site_name: WebSSH
copyright: WebSSH &copy; 2012-2025<br />Like my work? <a href="https://github.com/sponsors/isontheline">Sponsors</a> and <a href="https://www.buymeacoffee.com/isontheline">Coffees</a> are welcome!
theme:
  name: material
  custom_dir: overrides
  logo: images/webssh-logo.png
  favicon: images/favicon.ico
  font: false
  palette:
    scheme: preference
  features:
    - navigation.tabs
extra_css:
  - stylesheets/extra.css?20251102B
  - stylesheets/autorag.css?20251102B
extra_javascript:
  - javascripts/extra.js?20251102B
  - javascripts/autorag.js?20251102B
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/isontheline/pro.webssh.net
    - icon: fontawesome/solid/heart
      link: https://github.com/sponsors/isontheline
    - icon: fontawesome/solid/mug-saucer
      link: https://www.buymeacoffee.com/isontheline
    - icon: fontawesome/solid/sun
      link: https://wolf.solar
plugins:
  - search
  - git-revision-date-localized:
      type: date
  - redirects:
      redirect_maps:
        'documentation/pricing-fr.md': 'documentation/pricing.md'
        'documentation/changelog/15.md': 'documentation/changelog/history/15.md'
        'documentation/changelog/16.md': 'documentation/changelog/history/16.md'
        'documentation/changelog/17.md': 'documentation/changelog/history/17.md'
        'documentation/changelog/18.md': 'documentation/changelog/history/18.md'
        'documentation/changelog/19.md': 'documentation/changelog/history/19.md'
        'documentation/changelog/20.md': 'documentation/changelog/history/20.md'
        'documentation/changelog/21.md': 'documentation/changelog/history/21.md'
        'documentation/changelog/22.md': 'documentation/changelog/history/22.md'
        'documentation/changelog/23.md': 'documentation/changelog/history/23.md'
        'documentation/changelog/24.md': 'documentation/changelog/history/24.md'
        'documentation/help/howtos/link-connections-and-snippets.md': 'documentation/help/howtos/link-connections-using-tags.md'
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - footnotes